service: words-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  getAll: # A Function
    handler: handler.getAll # The file and module for this specific function.
    events: # The Events that trigger this Function
      - http: # This creates an API Gateway HTTP endpoint which can be used to trigger this function.  Learn more in "events/apigateway"
          path: words # Path for this endpoint
          method: get # HTTP method for this endpoint
          cors: true
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: words-local
            sources: [./seed-data.json]
resources:
  Resources:
    words-local:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: words-local
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
