service: words-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
functions:
  list:
    handler: handler.list
    events:
      - http:
          path: words
          method: get
          cors: true
  get:
    handler: handler.get
    events:
      - http:
          path: words/{id}
          method: get
          cors: true
  add:
    handler: handler.add
    events:
      - http:
          path: words
          method: post
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: words/{id}
          method: delete
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: words/{id}
          method: put
          cors: true
plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: words-local
            sources: [./seed-data.json]
resources:
  Resources:
    words-local:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: words-local
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
