service: words-api
provider:
  name: aws
  # role: arn:aws:iam::579729426660:role/LambdaDynamoAPIRole
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
functions:
  list:
    handler: handler.list
    events:
      - http:
          path: words
          method: get
          cors: true
  get:
    handler: handler.get
    events:
      - http:
          path: words/{id}
          method: get
          cors: true
  add:
    handler: handler.add
    events:
      - http:
          path: words
          method: post
          cors: true
  delet:
    handler: handler.delet
    events:
      - http:
          path: words/{id}
          method: delete
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: words/{id}
          method: put
          cors: true
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-domain-manager
custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
      seed: true
    seed:
      domain:
        sources:
          - table: words
            sources: [./seed-data.json]
  customDomain:
    domainName: api.thoughtfulmoose.com
    basePath: ''
    certificateName: 'api.thoughtfulmoose.com'
resources:
  Resources:
    words:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: words
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
