words-list:
  handler: ./src/handlers/words/src/list.handler
  events:
    - http:
        path: words
        method: get
        cors: true
        request:
          parameters:
            querystrings:
              name: false
              list: false
words-get:
  handler: ./src/handlers/words/src/get.handler
  events:
    - http:
        path: words/{id}
        method: get
        cors: true
words-add:
  handler: ./src/handlers/words/src/add.handler
  events:
    - http:
        path: words
        method: post
        cors: true
words-delete:
  handler: ./src/handlers/words/src/delete.handler
  events:
    - http:
        path: words/{id}
        method: delete
        cors: true
words-update:
  handler: ./src/handlers/words/src/update.handler
  events:
    - http:
        path: words/{id}
        method: put
        cors: true